query supplyMatches($id: ID!, $radius: Int, $cursor: CursorInput) {
  request: supply(id: $id) {
    skills {
      id
    }
  }

  result: matchSupply(cursor: $cursor, id: $id, radius: $radius) {
    pageInfo {
      offset
      pageSize
      hasNextPage
    }

    matches {
      distance
      percentage
      match: demand {
        id
        name
        description
        skills {
          name
          id
        }
        quantity
        salary: maxHourlySalary
        company {
          id
          name
          addressLine1
          postalCode
          city
          contact {
            firstName
            lastName
            pictureUrl
          }
          industry {
            name
          }
        }
      }
    }
  }
}
