#import "./DemandInfo.gql"
#import "./ContactInfo.gql"
#import "./CompanyInfo.gql"

query supplyMatches($id: ID!, $radius: Int, $cursor: CursorInput) {
  request: supply(id: $id) {
    id 
    skills {
      id
    }
  }

  result: matchSupply(cursor: $cursor, id: $id, radius: $radius) {
    pageInfo {
      offset
      pageSize
      hasNextPage
    }

    matches {
      distance
      percentage

      match: demand {
        ...DemandInfo

        company {
          ...CompanyInfo

          contact {
            ...ContactInfo
          }
        }
      }
    }
  }
}
