query DasboardTeams {
  me {
    id
    firstName
    lastName
    pictureUrl
  }

  companies{
    id
    postalCode
    city

    demands {
      id
      name
    }

    supplies {
      id
      name
    }
  }
}
