query check_state {  
    me {
        id

        companies {
            supplies {
                id
            }
            
            demands {
                id
            }
        }
    }
}

