query company($id:ID!) {
  company(id:$id) {
    id
    name
    demands {
      id
      isActive
      name
      description
      skills {
        id
        group
        name
      }
      quantity
      maxHourlySalary
      company {
        id
        addressLine1
        postalCode
        city
      }
    }
  }
}
