query supplyMatches($id:ID!){
  matchSupply(id:$id){
    matches{
      distance
      percentage
      supply{
        id
        name
        description 
        skills{
          id
          name
          group
        }
        quantity
        company{
          id
          name
          addressLine1
          postalCode
          city
        }
      }
    }
  }
}