query getTeams{
  companies{
    demands{
      id
      name
      isActive
      description
      skills{
        id 
        name
        group
      }
      quantity
      
    }
    supplies{
      id
      name
      isActive
      description
      skills{
        id 
        name
        group
      }
      quantity
    }
  }
}