query RegistrationCompany {
  industries {
    id
    name
  }
  
  me {
    id
    companies {
      id
      name
      addressLine1
      postalCode
      city
      industry {
        id
      }
    }
  }
}
