query getTeams{
  skills {
    id
    name
    group
  }

  teamNames

  companies{
    id
    addressLine1
    addressLine2
    addressLine3

    demands{
      id
      name
      isActive
      description
      skills{
        id
      }
      quantity

    }

    supplies{
      id
      name
      isActive
      description
      skills{
        id
      }
      quantity
    }
  }
}
